// GENERATED by build.js — do not edit by hand.

W.arcs["keepers-errand"] = {
  "id": "keepers-errand",
  "introduced_by": "npc:barliman-butterbur-ii",
  "quests_in_order": ["keepers-errand-1", "keepers-errand-2", "keepers-errand-3", "keepers-errand-4", "keepers-errand-5", "keepers-errand-6", "keepers-errand-7", "keepers-errand-8"],
  "regions": ["bree-land", "eriador-rivendell", "moria-hollin", "lothlorien-anduin", "dale-erebor", "rohan", "gondor-south", "mordor-ruin"],
  "summary": "Carry a sealed packet from Bree to the Black Gate, picking up additions at every great hold.",
  "title": "The Keeper's Errand"
};
