// GENERATED by build.js — do not edit by hand.

W.buildings["armory-of-edoras"] = {
  "description": "|",
  "entrance": {
    "x": 16,
    "y": 25
  },
  "id": "armory-of-edoras",
  "inventory_for_sale": [{
      "item": "spear-rohan",
      "price": 30,
      "stock": 3
    }, {
      "item": "shield-rohan",
      "price": 25,
      "stock": 3
    }],
  "name": "Armory of Edoras",
  "owner_npc": "aethelrun-smith",
  "services": ["shop:weapons"],
  "settlement": "edoras",
  "tags": ["smithy", "shop"],
  "type": "smithy",
  "world_pos": {
    "x": 68,
    "y": 155
  }
};
W.buildings["bruinen-archive"] = {
  "description": "|",
  "entrance": {
    "x": 16,
    "y": 25
  },
  "id": "bruinen-archive",
  "name": "Bruinen Archive",
  "owner_npc": "culunedhel",
  "services": [],
  "settlement": "imladris",
  "tags": ["lore", "archive"],
  "type": "tower",
  "world_pos": {
    "x": 120,
    "y": 45
  }
};
W.buildings["hall-of-fire"] = {
  "description": "|",
  "entrance": {
    "x": 28,
    "y": 23
  },
  "id": "hall-of-fire",
  "name": "Hall of Fire",
  "owner_npc": "lindir",
  "services": ["quest_board"],
  "settlement": "imladris",
  "tags": ["song", "ceremony"],
  "type": "temple",
  "world_pos": {
    "x": 132,
    "y": 43
  }
};
W.buildings["healers-hall"] = {
  "description": "|",
  "entrance": {
    "x": 22,
    "y": 25
  },
  "id": "healers-hall",
  "inventory_for_sale": [{
      "item": "lembas",
      "price": 8,
      "stock": 10
    }, {
      "item": "elvenbread-fresh",
      "price": 12,
      "stock": 5
    }],
  "name": "Healers' Hall",
  "owner_npc": "miriel-vardameldo",
  "services": ["healer", "shop:food"],
  "settlement": "imladris",
  "tags": ["heal", "shop"],
  "type": "shop",
  "world_pos": {
    "x": 126,
    "y": 45
  }
};
W.buildings["imladris-scriptorium"] = {
  "description": "|",
  "entrance": {
    "x": 16,
    "y": 23
  },
  "id": "imladris-scriptorium",
  "name": "Imladris Scriptorium",
  "owner_npc": "erestor-the-younger",
  "services": ["quest_board"],
  "settlement": "imladris",
  "tags": ["lore", "quiet"],
  "type": "temple",
  "world_pos": {
    "x": 120,
    "y": 43
  }
};
W.buildings["last-homely-house"] = {
  "description": "|",
  "entrance": {
    "x": 22,
    "y": 23
  },
  "id": "last-homely-house",
  "name": "The Last Homely House",
  "owner_npc": "elrohir",
  "services": ["inn"],
  "settlement": "imladris",
  "tags": ["safe", "iconic"],
  "type": "tower",
  "world_pos": {
    "x": 126,
    "y": 43
  }
};
W.buildings["mead-hall"] = {
  "description": "|",
  "entrance": {
    "x": 28,
    "y": 23
  },
  "id": "mead-hall",
  "inventory_for_sale": [{
      "item": "meduseld-mead",
      "price": 10,
      "stock": 12
    }, {
      "item": "waybread",
      "price": 6,
      "stock": 8
    }],
  "name": "The Mead Hall",
  "owner_npc": "hildwyn-hearth-warden",
  "services": ["inn", "shop:food"],
  "settlement": "edoras",
  "tags": ["inn", "food"],
  "type": "inn",
  "world_pos": {
    "x": 80,
    "y": 153
  }
};
W.buildings["meduseld"] = {
  "description": "|",
  "entrance": {
    "x": 22,
    "y": 23
  },
  "id": "meduseld",
  "name": "Meduseld",
  "owner_npc": "eomers-reeve",
  "services": ["inn", "quest_board"],
  "settlement": "edoras",
  "tags": ["iconic", "safe"],
  "type": "tower",
  "world_pos": {
    "x": 74,
    "y": 153
  }
};
W.buildings["stables-of-the-mark"] = {
  "description": "|",
  "entrance": {
    "x": 16,
    "y": 23
  },
  "id": "stables-of-the-mark",
  "inventory_for_sale": [{
      "item": "spear-rohan",
      "price": 35,
      "stock": 2
    }],
  "name": "Stables of the Mark",
  "owner_npc": "leofric-stablemaster",
  "services": ["shop:mounts"],
  "settlement": "edoras",
  "tags": ["horses", "shop"],
  "type": "shop",
  "world_pos": {
    "x": 68,
    "y": 153
  }
};
W.buildings["watchtower-of-edoras"] = {
  "description": "|",
  "entrance": {
    "x": 28,
    "y": 25
  },
  "id": "watchtower-of-edoras",
  "name": "Watchtower of Edoras",
  "owner_npc": "oswin-scout",
  "services": ["quest_board"],
  "settlement": "edoras",
  "tags": ["lookout"],
  "type": "tower",
  "world_pos": {
    "x": 80,
    "y": 155
  }
};
