// GENERATED by build.js — do not edit by hand.

W.buildings["bruinen-archive"] = {
  "description": "|",
  "entrance": {
    "x": 16,
    "y": 25
  },
  "id": "bruinen-archive",
  "name": "Bruinen Archive",
  "owner_npc": "culunedhel",
  "services": [],
  "settlement": "imladris",
  "tags": ["lore", "archive"],
  "type": "tower"
};
W.buildings["hall-of-fire"] = {
  "description": "|",
  "entrance": {
    "x": 28,
    "y": 23
  },
  "id": "hall-of-fire",
  "name": "Hall of Fire",
  "owner_npc": "lindir",
  "services": ["quest_board"],
  "settlement": "imladris",
  "tags": ["song", "ceremony"],
  "type": "temple"
};
W.buildings["healers-hall"] = {
  "description": "|",
  "entrance": {
    "x": 22,
    "y": 25
  },
  "id": "healers-hall",
  "inventory_for_sale": [{
      "item": "lembas",
      "price": 8,
      "stock": 10
    }, {
      "item": "elvenbread-fresh",
      "price": 12,
      "stock": 5
    }],
  "name": "Healers' Hall",
  "owner_npc": "miriel-vardameldo",
  "services": ["healer", "shop:food"],
  "settlement": "imladris",
  "tags": ["heal", "shop"],
  "type": "shop"
};
W.buildings["imladris-scriptorium"] = {
  "description": "|",
  "entrance": {
    "x": 16,
    "y": 23
  },
  "id": "imladris-scriptorium",
  "name": "Imladris Scriptorium",
  "owner_npc": "erestor-the-younger",
  "services": ["quest_board"],
  "settlement": "imladris",
  "tags": ["lore", "quiet"],
  "type": "temple"
};
W.buildings["last-homely-house"] = {
  "description": "|",
  "entrance": {
    "x": 22,
    "y": 23
  },
  "id": "last-homely-house",
  "name": "The Last Homely House",
  "owner_npc": "elrohir",
  "services": ["inn"],
  "settlement": "imladris",
  "tags": ["safe", "iconic"],
  "type": "tower"
};
