// GENERATED by build.js — do not edit by hand.

W.classs["dwarf"] = {
  "can_use": {
    "bow": true,
    "magic_items": true,
    "melee": true
  },
  "id": "dwarf",
  "lore": "Stout, slow-moving, impossibly hard to kill.",
  "name": "Dwarf of Erebor",
  "signature_ability": "forage",
  "starting_inventory": ["axe-dwarven", "shield-dwarven", "dwarf-bread", "rune-stone"],
  "starting_pos": {
    "x": 20,
    "y": 20
  },
  "starting_region": "dale-erebor",
  "stats": {
    "atk": 16,
    "def": 7,
    "hp": 150,
    "sight": 200,
    "speed": 100
  }
};
W.classs["elf-noldor"] = {
  "can_use": {
    "bow": true,
    "magic_items": true,
    "melee": true
  },
  "id": "elf-noldor",
  "lore": "Loremaster and warrior both. Has seen ages turn.",
  "name": "Noldor Elf",
  "signature_ability": "track",
  "starting_inventory": ["sword-elven", "bow-yew", "lembas", "phial-of-galadriel"],
  "starting_pos": {
    "x": 20,
    "y": 20
  },
  "starting_region": "eriador-rivendell",
  "stats": {
    "atk": 13,
    "def": 4,
    "hp": 100,
    "sight": 260,
    "speed": 130
  }
};
W.classs["gondorian"] = {
  "can_use": {
    "bow": true,
    "magic_items": false,
    "melee": true
  },
  "id": "gondorian",
  "lore": "Citadel-trained. Drilled in phalanx and patrol.",
  "name": "Gondorian Soldier",
  "signature_ability": "shieldwall",
  "starting_inventory": ["sword-gondor", "shield-gondor", "waybread"],
  "starting_pos": {
    "x": 20,
    "y": 20
  },
  "starting_region": "gondor-south",
  "stats": {
    "atk": 14,
    "def": 5,
    "hp": 120,
    "sight": 210,
    "speed": 115
  }
};
W.classs["hobbit"] = {
  "can_use": {
    "bow": true,
    "magic_items": true,
    "melee": true
  },
  "id": "hobbit",
  "lore": "Small of stature, large of appetite, unexpectedly resilient.",
  "name": "Hobbit of the Shire",
  "signature_ability": "stealth",
  "starting_inventory": ["short-blade", "sling", "lembas", "rope", "mathom"],
  "starting_pos": {
    "x": 20,
    "y": 20
  },
  "starting_region": "shire",
  "stats": {
    "atk": 9,
    "def": 2,
    "hp": 85,
    "sight": 200,
    "speed": 108
  }
};
W.classs["ranger-of-the-north"] = {
  "can_use": {
    "bow": true,
    "magic_items": true,
    "melee": true
  },
  "id": "ranger-of-the-north",
  "lore": "A Dúnadan of the Grey Company — swift, silent, long-lived.",
  "name": "Ranger of the North",
  "signature_ability": "stealth",
  "starting_inventory": ["sword-elven", "bow-yew", "lembas", "rope", "elven-cloak"],
  "starting_pos": {
    "x": 20,
    "y": 18
  },
  "starting_region": "bree-land",
  "stats": {
    "atk": 14,
    "def": 3,
    "hp": 110,
    "sight": 240,
    "speed": 120
  }
};
W.classs["rohirrim"] = {
  "can_use": {
    "bow": false,
    "magic_items": false,
    "melee": true
  },
  "id": "rohirrim",
  "lore": "Horse-lords of the Mark. Swift in open country.",
  "name": "Rohirrim Rider",
  "signature_ability": "shieldwall",
  "starting_inventory": ["spear-rohan", "shield-rohan", "waybread"],
  "starting_pos": {
    "x": 20,
    "y": 20
  },
  "starting_region": "rohan",
  "stats": {
    "atk": 15,
    "def": 5,
    "hp": 130,
    "sight": 220,
    "speed": 140
  }
};
