// GENERATED by build.js — do not edit by hand.

W.dialogues["bard-iron"] = {
  "id": "bard-iron",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "iron-started",
              "type": "flag",
              "value": true
            }, {
              "id": "iron-for-the-south",
              "type": "quest_start"
            }],
          "next": null,
          "text": "Aye."
        }],
      "text": "The wagons leave at dawn. Keep the axle wheels unbroken."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "I shall."
        }],
      "text": "Mind the hills east of the Anduin."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "iron-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 15,
              "faction": "dwarves-of-erebor",
              "type": "faction_rep"
            }, {
              "delta": 30,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "A purse of Ereborian silver, well earned."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "iron-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I'll ride with them."
        }, {
          "cond": {
            "raw": "flag:iron-started && !flag:iron-delivered",
            "type": "raw"
          },
          "next": "progress",
          "text": "Road clear?"
        }, {
          "cond": {
            "name": "iron-delivered",
            "type": "flag"
          },
          "next": "reward",
          "text": "Thanks again."
        }, {
          "next": null,
          "text": "Fare well."
        }],
      "text": "Well met, traveller. [if: !flag:iron-started] We've a caravan bound for Gondor — could use another sword."
    }
  },
  "speaker": "bard-iii",
  "start": "start"
};
W.dialogues["barliman-welcome"] = {
  "id": "barliman-welcome",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "Aye."
        }],
      "text": "The Greenway runs south from the crossroads. Ride safe."
    },
    "news": {
      "choices": [{
          "effects": [{
              "name": "accepted-greenway",
              "type": "flag",
              "value": true
            }, {
              "id": "strangers-on-the-greenway",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I'll ride there."
        }, {
          "next": "start",
          "text": "Not my errand."
        }],
      "text": "Travelers say orc-scouts skulk along the Greenway south of town. If a soul of your cut were to scatter them, the Kingdom would remember."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Understood."
        }],
      "text": "Take care down there — keep the road to your right."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "greenway-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 25,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Word came back: the road's clear. Here — a traveller's pouch on the house."
    },
    "room": {
      "choices": [{
          "next": "start",
          "text": "My thanks."
        }],
      "text": "A fine room, as always. Sleep well."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "accepted-greenway",
            "type": "not_flag"
          },
          "next": "news",
          "text": "What's the word?"
        }, {
          "cond": {
            "raw": "flag:accepted-greenway && !flag:greenway-clear",
            "type": "raw"
          },
          "next": "progress",
          "text": "Any progress on the Greenway?"
        }, {
          "cond": {
            "name": "greenway-clear",
            "type": "flag"
          },
          "next": "reward",
          "text": "It's quiet now."
        }, {
          "effects": [{
              "delta": -5,
              "type": "gold"
            }, {
              "delta": 30,
              "type": "hp"
            }, {
              "name": "slept-at-pony",
              "type": "flag",
              "value": true
            }],
          "next": "room",
          "text": "A room, please."
        }, {
          "next": null,
          "text": "Another time."
        }],
      "text": "Well met! [if: !flag:accepted-greenway] The roads have been restless of late. Care to hear what I've heard?"
    }
  },
  "speaker": "barliman-butterbur-ii",
  "start": "start"
};
W.dialogues["beregond-bridge"] = {
  "id": "beregond-bridge",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "bridge-started",
              "type": "flag",
              "value": true
            }, {
              "id": "bridge-of-stone",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I shall."
        }],
      "text": "The south span. Keep the king's peace."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Aye."
        }],
      "text": "Swift strike, sure foot."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "bridge-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 20,
              "faction": "reunited-kingdom",
              "type": "faction_rep"
            }, {
              "delta": 25,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "A Citadel commendation. And coin besides."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "bridge-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "Point the way."
        }, {
          "cond": {
            "raw": "flag:bridge-started && !flag:bridge-done",
            "type": "raw"
          },
          "next": "progress",
          "text": "Bridge held?"
        }, {
          "cond": {
            "name": "bridge-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Bridge is open?"
        }, {
          "next": null,
          "text": "Later."
        }],
      "text": "Hail, friend of the Kingdom. [if: !flag:bridge-started] Bandits set on the new bridge at dusk. Would you lend a blade?"
    }
  },
  "speaker": "faramirs-steward",
  "start": "start"
};
W.dialogues["deorwin-hoofbeats"] = {
  "id": "deorwin-hoofbeats",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "hoofbeats-started",
              "type": "flag",
              "value": true
            }, {
              "id": "hoofbeats-in-the-wold",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }],
      "text": "Take a Rohirric spear. Return ere the moon turns."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Aye."
        }],
      "text": "Fast hooves, truer spears."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "hoofbeats-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 15,
              "faction": "rohirrim",
              "type": "faction_rep"
            }, {
              "delta": 20,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "The Mark remembers you, friend."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "hoofbeats-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I'll ride."
        }, {
          "cond": {
            "raw": "flag:hoofbeats-started && !flag:hoofbeats-done",
            "type": "raw"
          },
          "next": "progress",
          "text": "Raiders still out?"
        }, {
          "cond": {
            "name": "hoofbeats-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Wold is quiet."
        }, {
          "next": null,
          "text": "Another day."
        }],
      "text": "Hail, rider. [if: !flag:hoofbeats-started] Easterling raiders trouble the Wold. Would you ride north?"
    }
  },
  "speaker": "eomers-reeve",
  "start": "start"
};
W.dialogues["elrohir-books"] = {
  "id": "elrohir-books",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "books-started",
              "type": "flag",
              "value": true
            }, {
              "id": "the-books-of-elrond",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I shall."
        }],
      "text": "Bring them to the library. Handle them gently."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Understood."
        }],
      "text": "They are likely south, by the old road."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "books-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 20,
              "faction": "imladris-elves",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Hannon le. Take this phial — a gift long kept."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "books-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I will search."
        }, {
          "cond": {
            "raw": "flag:books-started && !flag:books-done",
            "type": "raw"
          },
          "next": "progress",
          "text": "Still searching?"
        }, {
          "cond": {
            "name": "books-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "They are safe."
        }, {
          "next": null,
          "text": "Another time."
        }],
      "text": "Mae govannen. [if: !flag:books-started] Some annals of my father were left behind in the hills. Would you fetch them?"
    }
  },
  "speaker": "elrohir",
  "start": "start"
};
W.dialogues["goldberry-wight"] = {
  "id": "goldberry-wight",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "wight-started",
              "type": "flag",
              "value": true
            }, {
              "id": "a-wight-returns",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }],
      "text": "Take heart. Sing if the dark closes."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Thank you."
        }],
      "text": "Tom's name is a light. Use it if need be."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "wight-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 10,
              "faction": "rangers-of-the-north",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "And with you."
        }],
      "text": "The water is clear again. Peace go with you."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "wight-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I'll put it down."
        }, {
          "cond": {
            "raw": "flag:wight-started && !flag:wight-done",
            "type": "raw"
          },
          "next": "progress",
          "text": "Still restless?"
        }, {
          "cond": {
            "name": "wight-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "The Downs are quiet."
        }, {
          "next": null,
          "text": "Go well."
        }],
      "text": "Come, merry dol. [if: !flag:wight-started] A barrow stirs on the Downs — it should not."
    }
  },
  "speaker": "goldberry",
  "start": "start"
};
W.dialogues["orophin-mallorn"] = {
  "id": "orophin-mallorn",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "mallorn-started",
              "type": "flag",
              "value": true
            }, {
              "id": "the-last-mallorn",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }],
      "text": "Take this bow. Strike any who lay hand on the sapling."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "I will."
        }],
      "text": "The sapling stands. Keep the watch."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "mallorn-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 15,
              "faction": "galadhrim",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "Hannon le."
        }],
      "text": "The tree has rooted. Accept this lembas — little though it is."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "mallorn-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I will."
        }, {
          "cond": {
            "raw": "flag:mallorn-started && !flag:mallorn-saved",
            "type": "raw"
          },
          "next": "progress",
          "text": "Has it held?"
        }, {
          "cond": {
            "name": "mallorn-saved",
            "type": "flag"
          },
          "next": "reward",
          "text": "The wood is well?"
        }, {
          "next": null,
          "text": "Another time."
        }],
      "text": "Mae govannen. [if: !flag:mallorn-started] A young mallorn falters. Would you guard it a while?"
    }
  },
  "speaker": "haldirs-successor",
  "start": "start"
};
W.dialogues["sam-missing-mathom"] = {
  "id": "sam-missing-mathom",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "I'll be off."
        }],
      "text": "Bless you! The pond's south of the plaza."
    },
    "ask": {
      "choices": [{
          "effects": [{
              "name": "accepted-mathom",
              "type": "flag",
              "value": true
            }, {
              "id": "missing-mathom",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I'll bring it back."
        }, {
          "next": "start",
          "text": "Sorry, no."
        }],
      "text": "You see, I've misplaced a mathom — small copper thing, belonged to my great-grand-dad. I last saw it by the pond. Would you fetch it, if you spy it?"
    },
    "ask-found": {
      "choices": [{
          "effects": [{
              "name": "found-mathom",
              "type": "flag",
              "value": true
            }, {
              "id": "missing-mathom",
              "type": "quest_complete"
            }, {
              "delta": 15,
              "type": "gold"
            }, {
              "delta": 20,
              "type": "hp"
            }],
          "next": "return",
          "text": "Found it."
        }, {
          "next": "START",
          "text": "Not yet."
        }, {
          "next": null,
          "text": "Never mind."
        }],
      "text": "Any luck? The pond's south of the square."
    },
    "farewell": {
      "choices": [{
          "next": null,
          "text": "Likewise."
        }],
      "text": "Fair travels, friend."
    },
    "return": {
      "choices": [{
          "next": null,
          "text": "Happy to help."
        }],
      "text": "Oh splendid — my thanks! Here, take a few coppers and a bite to eat."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "accepted-mathom",
            "type": "not_flag"
          },
          "next": "ask",
          "text": "I have."
        }, {
          "cond": {
            "raw": "flag:accepted-mathom && !flag:found-mathom",
            "type": "raw"
          },
          "next": "ask-found",
          "text": "Have you found it yet?"
        }, {
          "cond": {
            "name": "found-mathom",
            "type": "flag"
          },
          "next": "farewell",
          "text": "Safe pocketing to you."
        }, {
          "next": null,
          "text": "Not today."
        }],
      "text": "Ah, good day to you! Ah — [if: !flag:accepted-mathom] have you a moment to help an old hobbit?"
    }
  },
  "speaker": "sam-gamgee-the-younger",
  "start": "start"
};
W.dialogues["thorin-relight"] = {
  "id": "thorin-relight",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "Aye."
        }],
      "text": "May the flame hold, friend."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Understood."
        }],
      "text": "Keep to the lamps and the lamps to you."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "relight-lamps-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 20,
              "faction": "dwarves-of-erebor",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Durin's sign shines again. Here, a rune-stone for your troubles."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "relight-lamps-started",
            "type": "not_flag"
          },
          "next": "task",
          "text": "Tell me."
        }, {
          "cond": {
            "raw": "flag:relight-lamps-started && !flag:relight-lamps-done",
            "type": "raw"
          },
          "next": "progress",
          "text": "Still at it?"
        }, {
          "cond": {
            "name": "relight-lamps-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Mithril for ye."
        }, {
          "next": null,
          "text": "Farewell."
        }],
      "text": "Welcome to the Doors of Durin, stranger. [if: !flag:relight-lamps-started] We've a task a stout arm might lend to."
    },
    "task": {
      "choices": [{
          "effects": [{
              "name": "relight-lamps-started",
              "type": "flag",
              "value": true
            }, {
              "id": "relight-the-lamps",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I'll light them."
        }, {
          "next": "start",
          "text": "Not my path."
        }],
      "text": "The old way-marker lamps along the east road have gone dark. Light them and we'll know the path is safe again."
    }
  },
  "speaker": "thorin-iv",
  "start": "start"
};
W.dialogues["warden-ash"] = {
  "id": "warden-ash",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "ash-started",
              "type": "flag",
              "value": true
            }, {
              "id": "ash-and-ember",
              "type": "quest_start"
            }],
          "next": null,
          "text": "Consider it done."
        }],
      "text": "South of the watchfort. Burn it out."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Aye."
        }],
      "text": "No shade must follow you back."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "ash-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 25,
              "faction": "reunited-kingdom",
              "type": "faction_rep"
            }, {
              "delta": 30,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "The Kingdom sends her thanks — and a sword."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "ash-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "Where?"
        }, {
          "cond": {
            "raw": "flag:ash-started && !flag:ash-done",
            "type": "raw"
          },
          "next": "progress",
          "text": "Still stirring?"
        }, {
          "cond": {
            "name": "ash-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Fire is out?"
        }, {
          "next": null,
          "text": "Not today."
        }],
      "text": "You pass the gate at a good hour. [if: !flag:ash-started] We've a warren that must be cleared."
    }
  },
  "speaker": "warden-of-morannon",
  "start": "start"
};
