// GENERATED by build.js — do not edit by hand.

W.dialogues["aethelrun-armory"] = {
  "id": "aethelrun-armory",
  "nodes": {
    "shop": {
      "choices": [{
          "next": "start",
          "text": "I'll browse."
        }],
      "text": "A Rohirric spear, thirty silver. A round shield, twenty-five."
    },
    "start": {
      "choices": [{
          "next": "shop",
          "text": "Show me your wares."
        }, {
          "next": null,
          "text": "Another day."
        }],
      "text": "Gold or iron?"
    }
  },
  "speaker": "aethelrun-smith",
  "start": "start"
};
W.dialogues["bard-iron"] = {
  "id": "bard-iron",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "iron-started",
              "type": "flag",
              "value": true
            }, {
              "id": "iron-for-the-south",
              "type": "quest_start"
            }],
          "next": null,
          "text": "Aye."
        }],
      "text": "The wagons leave at dawn. Keep the axle wheels unbroken."
    },
    "errand-receive": {
      "choices": [{
          "effects": [{
              "name": "errand-leg-4-delivered",
              "type": "flag",
              "value": true
            }, {
              "name": "errand-leg-5",
              "type": "flag",
              "value": true
            }, {
              "id": "keepers-errand-4",
              "type": "quest_complete"
            }, {
              "id": "keepers-errand-5",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }, {
          "next": "start",
          "text": "A moment."
        }],
      "text": "Hand it here. I add an Ereborian script. Bear the packet now south to the Reeve at Edoras."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "I shall."
        }],
      "text": "Mind the hills east of the Anduin."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "iron-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 15,
              "faction": "dwarves-of-erebor",
              "type": "faction_rep"
            }, {
              "delta": 30,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "A purse of Ereborian silver, well earned."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "iron-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I'll ride with them."
        }, {
          "cond": {
            "clauses": [{
                "name": "iron-started",
                "type": "flag"
              }, {
                "name": "iron-delivered",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Road clear?"
        }, {
          "cond": {
            "name": "iron-delivered",
            "type": "flag"
          },
          "next": "reward",
          "text": "Thanks again."
        }, {
          "cond": {
            "clauses": [{
                "name": "errand-leg-4",
                "type": "flag"
              }, {
                "name": "errand-leg-5",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "errand-receive",
          "text": "I bear a Keeper's packet."
        }, {
          "next": null,
          "text": "Fare well."
        }],
      "text": "Well met, traveller. We've a caravan bound for Gondor — could use another sword."
    }
  },
  "speaker": "bard-iii",
  "start": "start"
};
W.dialogues["barliman-welcome"] = {
  "id": "barliman-welcome",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "Aye."
        }],
      "text": "The Greenway runs south from the crossroads. Ride safe."
    },
    "errand-1": {
      "choices": [{
          "effects": [{
              "name": "errand-leg-1",
              "type": "flag",
              "value": true
            }, {
              "id": "keepers-errand-1",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I'll bear it."
        }, {
          "next": "start",
          "text": "Not now."
        }],
      "text": "Hush, then. Halbarad left this sealed letter — bear it east to Elrohir at Rivendell."
    },
    "news": {
      "choices": [{
          "effects": [{
              "name": "accepted-greenway",
              "type": "flag",
              "value": true
            }, {
              "id": "strangers-on-the-greenway",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I'll ride there."
        }, {
          "next": "start",
          "text": "Not my errand."
        }],
      "text": "Travelers say orc-scouts skulk along the Greenway south of town. If a soul of your cut were to scatter them, the Kingdom would remember."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Understood."
        }],
      "text": "Take care down there — keep the road to your right."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "greenway-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 25,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Word came back: the road's clear. Here — a traveller's pouch on the house."
    },
    "room": {
      "choices": [{
          "next": "start",
          "text": "My thanks."
        }],
      "text": "A fine room, as always. Sleep well."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "accepted-greenway",
            "type": "not_flag"
          },
          "next": "news",
          "text": "What's the word?"
        }, {
          "cond": {
            "clauses": [{
                "name": "accepted-greenway",
                "type": "flag"
              }, {
                "name": "greenway-clear",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Any progress on the Greenway?"
        }, {
          "cond": {
            "name": "greenway-clear",
            "type": "flag"
          },
          "next": "reward",
          "text": "It's quiet now."
        }, {
          "effects": [{
              "delta": -5,
              "type": "gold"
            }, {
              "delta": 30,
              "type": "hp"
            }, {
              "name": "slept-at-pony",
              "type": "flag",
              "value": true
            }],
          "next": "room",
          "text": "A room, please."
        }, {
          "cond": {
            "name": "errand-leg-1",
            "type": "not_flag"
          },
          "next": "errand-1",
          "text": "Heard of the Keeper's Errand?"
        }, {
          "next": null,
          "text": "Another time."
        }],
      "text": "Well met! The roads have been restless of late. Care to hear what I've heard?"
    }
  },
  "speaker": "barliman-butterbur-ii",
  "start": "start"
};
W.dialogues["beregond-bridge"] = {
  "id": "beregond-bridge",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "bridge-started",
              "type": "flag",
              "value": true
            }, {
              "id": "bridge-of-stone",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I shall."
        }],
      "text": "The south span. Keep the king's peace."
    },
    "errand-receive": {
      "choices": [{
          "effects": [{
              "name": "errand-leg-6-delivered",
              "type": "flag",
              "value": true
            }, {
              "name": "errand-leg-7",
              "type": "flag",
              "value": true
            }, {
              "id": "keepers-errand-6",
              "type": "quest_complete"
            }, {
              "id": "keepers-errand-7",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }, {
          "next": "start",
          "text": "A moment."
        }],
      "text": "Hand it here. The white tree, sealed. Bear the packet now east to the Warden at the Morannon."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Aye."
        }],
      "text": "Swift strike, sure foot."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "bridge-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 20,
              "faction": "reunited-kingdom",
              "type": "faction_rep"
            }, {
              "delta": 25,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "A Citadel commendation. And coin besides."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "bridge-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "Point the way."
        }, {
          "cond": {
            "clauses": [{
                "name": "bridge-started",
                "type": "flag"
              }, {
                "name": "bridge-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Bridge held?"
        }, {
          "cond": {
            "name": "bridge-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Bridge is open?"
        }, {
          "cond": {
            "clauses": [{
                "name": "errand-leg-6",
                "type": "flag"
              }, {
                "name": "errand-leg-7",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "errand-receive",
          "text": "I bear a Keeper's packet."
        }, {
          "next": null,
          "text": "Later."
        }],
      "text": "Hail, friend of the Kingdom. Bandits set on the new bridge at dusk. Would you lend a blade?"
    }
  },
  "speaker": "faramirs-steward",
  "start": "start"
};
W.dialogues["culunedhel-archive"] = {
  "id": "culunedhel-archive",
  "nodes": {
    "deliver": {
      "choices": [{
          "effects": [{
              "name": "lost-page-retrieved",
              "type": "flag",
              "value": true
            }],
          "next": null,
          "text": "Understood."
        }],
      "text": "Good. Give it to Erestor, not to me. My hands no longer touch vellum."
    },
    "lost-page-hint": {
      "choices": [{
          "next": null,
          "text": "I shall."
        }],
      "text": "Speak with Erestor in the scriptorium. He knows what he lost."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "lost-page-started",
            "type": "flag"
          },
          "next": "deliver",
          "text": "I have it."
        }, {
          "cond": {
            "name": "lost-page-started",
            "type": "not_flag"
          },
          "next": "lost-page-hint",
          "text": "What leaf?"
        }, {
          "next": null,
          "text": "I meant no harm."
        }],
      "text": "You again. The leaf sits in the fourth bay, among the Cardolan rolls. Take it, carefully, and I will let you leave."
    }
  },
  "speaker": "culunedhel",
  "start": "start"
};
W.dialogues["deorwin-hoofbeats"] = {
  "id": "deorwin-hoofbeats",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "hoofbeats-started",
              "type": "flag",
              "value": true
            }, {
              "id": "hoofbeats-in-the-wold",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }],
      "text": "Take a Rohirric spear. Return ere the moon turns."
    },
    "errand-receive": {
      "choices": [{
          "effects": [{
              "name": "errand-leg-5-delivered",
              "type": "flag",
              "value": true
            }, {
              "name": "errand-leg-6",
              "type": "flag",
              "value": true
            }, {
              "id": "keepers-errand-5",
              "type": "quest_complete"
            }, {
              "id": "keepers-errand-6",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }, {
          "next": "start",
          "text": "A moment."
        }],
      "text": "Hand it here. The white horse-seal of the Mark, added. Bear the packet now east to Beregond at Osgiliath."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Aye."
        }],
      "text": "Fast hooves, truer spears."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "hoofbeats-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 15,
              "faction": "rohirrim",
              "type": "faction_rep"
            }, {
              "delta": 20,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "The Mark remembers you, friend."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "hoofbeats-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I'll ride."
        }, {
          "cond": {
            "clauses": [{
                "name": "hoofbeats-started",
                "type": "flag"
              }, {
                "name": "hoofbeats-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Raiders still out?"
        }, {
          "cond": {
            "name": "hoofbeats-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Wold is quiet."
        }, {
          "cond": {
            "clauses": [{
                "name": "errand-leg-5",
                "type": "flag"
              }, {
                "name": "errand-leg-6",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "errand-receive",
          "text": "I bear a Keeper's packet."
        }, {
          "next": null,
          "text": "Another day."
        }],
      "text": "Hail, rider. Easterling raiders trouble the Wold. Would you ride north?"
    }
  },
  "speaker": "eomers-reeve",
  "start": "start"
};
W.dialogues["elrohir-books"] = {
  "id": "elrohir-books",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "books-started",
              "type": "flag",
              "value": true
            }, {
              "id": "the-books-of-elrond",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I shall."
        }],
      "text": "Bring them to the library. Handle them gently."
    },
    "errand-receive": {
      "choices": [{
          "effects": [{
              "name": "errand-leg-1-delivered",
              "type": "flag",
              "value": true
            }, {
              "name": "errand-leg-2",
              "type": "flag",
              "value": true
            }, {
              "id": "keepers-errand-1",
              "type": "quest_complete"
            }, {
              "id": "keepers-errand-2",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }, {
          "next": "start",
          "text": "A moment."
        }],
      "text": "Hand it here. I add a leaf of counsel. Bear the packet now to Thorin IV at Moria's West-gate."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Understood."
        }],
      "text": "They are likely south, by the old road."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "books-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 20,
              "faction": "imladris-elves",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Hannon le. Take this phial — a gift long kept."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "books-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I will search."
        }, {
          "cond": {
            "clauses": [{
                "name": "books-started",
                "type": "flag"
              }, {
                "name": "books-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Still searching?"
        }, {
          "cond": {
            "name": "books-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "They are safe."
        }, {
          "cond": {
            "clauses": [{
                "name": "errand-leg-1",
                "type": "flag"
              }, {
                "name": "errand-leg-2",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "errand-receive",
          "text": "I bear a sealed letter."
        }, {
          "next": null,
          "text": "Another time."
        }],
      "text": "Mae govannen. Some annals of my father were left behind in the hills. Would you fetch them?"
    }
  },
  "speaker": "elrohir",
  "start": "start"
};
W.dialogues["erestor-scriptorium"] = {
  "id": "erestor-scriptorium",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "lost-page-started",
              "type": "flag",
              "value": true
            }, {
              "id": "the-lost-page",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I shall."
        }],
      "text": "Hannon le. Bring it unstained if you can."
    },
    "discover": {
      "choices": [{
          "effects": [{
              "name": "verse-done",
              "type": "flag",
              "value": true
            }],
          "next": null,
          "text": "Thank you."
        }],
      "text": "Here. Between the verses of Fëanor's apology and the list of ships."
    },
    "lost-page": {
      "choices": [{
          "next": "accept",
          "text": "I will look."
        }, {
          "next": "start",
          "text": "Another day."
        }],
      "text": "A leaf of Arnor's roll has fallen from its binding — find it in the south archive and bring it back."
    },
    "start": {
      "choices": [{
          "cond": {
            "clauses": [{
                "name": "verse-started",
                "type": "flag"
              }, {
                "name": "verse-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "discover",
          "text": "I would read it."
        }, {
          "cond": {
            "name": "lost-page-started",
            "type": "not_flag"
          },
          "next": "lost-page",
          "text": "About a lost page."
        }, {
          "next": null,
          "text": "Just passing."
        }],
      "text": "You walk softly — good. Lindir's line? I set it on the long table, beside the sea-songs. Read it if you wish."
    }
  },
  "speaker": "erestor-the-younger",
  "start": "start"
};
W.dialogues["goldberry-wight"] = {
  "id": "goldberry-wight",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "wight-started",
              "type": "flag",
              "value": true
            }, {
              "id": "a-wight-returns",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }],
      "text": "Take heart. Sing if the dark closes."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Thank you."
        }],
      "text": "Tom's name is a light. Use it if need be."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "wight-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 10,
              "faction": "rangers-of-the-north",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "And with you."
        }],
      "text": "The water is clear again. Peace go with you."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "wight-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I'll put it down."
        }, {
          "cond": {
            "clauses": [{
                "name": "wight-started",
                "type": "flag"
              }, {
                "name": "wight-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Still restless?"
        }, {
          "cond": {
            "name": "wight-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "The Downs are quiet."
        }, {
          "next": null,
          "text": "Go well."
        }],
      "text": "Come, merry dol. A barrow stirs on the Downs — it should not."
    }
  },
  "speaker": "goldberry",
  "start": "start"
};
W.dialogues["hildwyn-mead"] = {
  "id": "hildwyn-mead",
  "nodes": {
    "drink": {
      "choices": [{
          "effects": [{
              "delta": -10,
              "type": "gold"
            }, {
              "delta": 20,
              "type": "hp"
            }],
          "next": null,
          "text": "Long life."
        }],
      "text": "Ten silver. Long life. (heal 20)"
    },
    "news": {
      "choices": [{
          "next": "start",
          "text": "Noted."
        }],
      "text": "Oswin atop the watchtower saw eastern horsemen two nights past. Déorwin will\nknow more."
    },
    "start": {
      "choices": [{
          "next": "drink",
          "text": "Pour me a horn."
        }, {
          "next": "news",
          "text": "Any news?"
        }, {
          "next": null,
          "text": "Another day."
        }],
      "text": "Welcome, rider. The fire is warm, the mead is fresh."
    }
  },
  "speaker": "hildwyn-hearth-warden",
  "start": "start"
};
W.dialogues["leofric-stables"] = {
  "id": "leofric-stables",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "lost-horse-started",
              "type": "flag",
              "value": true
            }, {
              "id": "horse-of-the-mark",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I understand."
        }],
      "text": "He'll be east of here, near the stream."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "lost-horse-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 25,
              "type": "gold"
            }, {
              "delta": 10,
              "faction": "rohirrim",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Well ridden. The Mark thanks you."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "lost-horse-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I'll look for him."
        }, {
          "cond": {
            "name": "lost-horse-found",
            "type": "flag"
          },
          "next": "reward",
          "text": "I found the colt."
        }, {
          "next": null,
          "text": "Later."
        }],
      "text": "Hail, stranger. A bay colt, Fréawine, broke his tether last night. Worth three silver to bring him in."
    }
  },
  "speaker": "leofric-stablemaster",
  "start": "start"
};
W.dialogues["lindir-verse"] = {
  "id": "lindir-verse",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "Farewell."
        }],
      "text": "Hannon le."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "I shall look."
        }],
      "text": "In the scriptorium, perhaps — or where annals gather."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "verse-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 30,
              "type": "hp"
            }, {
              "delta": 15,
              "type": "gold"
            }, {
              "delta": 15,
              "faction": "imladris-elves",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "At last — the song is whole. Take a lembas wafer; it is little thanks for so much."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "verse-started",
            "type": "not_flag"
          },
          "next": "task",
          "text": "I will look."
        }, {
          "cond": {
            "clauses": [{
                "name": "verse-started",
                "type": "flag"
              }, {
                "name": "verse-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Still seeking?"
        }, {
          "cond": {
            "name": "verse-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Here is the line."
        }, {
          "next": null,
          "text": "Another time."
        }],
      "text": "Mae govannen. A verse of my own making — I have lost a line. Would you seek it in the old hall?"
    },
    "task": {
      "choices": [{
          "effects": [{
              "name": "verse-started",
              "type": "flag",
              "value": true
            }, {
              "id": "a-forgotten-verse",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I will find it."
        }, {
          "next": "start",
          "text": "A lesser errand."
        }],
      "text": "A leaf of vellum, lost among the annals. My father's hand is on it."
    }
  },
  "speaker": "lindir",
  "start": "start"
};
W.dialogues["miriel-heal"] = {
  "id": "miriel-heal",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "kingsfoil-errand-started",
              "type": "flag",
              "value": true
            }, {
              "id": "kingsfoil-for-imladris",
              "type": "quest_start"
            }],
          "next": null,
          "text": "Understood."
        }],
      "text": "Three stems will be enough. Keep them out of direct sun."
    },
    "heal": {
      "choices": [{
          "effects": [{
              "delta": 40,
              "type": "hp"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Rest a moment. Drink this. (+40 hp)"
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "kingsfoil-errand-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 30,
              "type": "hp"
            }, {
              "delta": 20,
              "type": "gold"
            }, {
              "delta": 10,
              "faction": "imladris-elves",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "Hannon le."
        }],
      "text": "These will last the season. Take a loaf of fresh elven-bread with my thanks."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "kingsfoil-errand-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I will gather."
        }, {
          "cond": {
            "name": "kingsfoil-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "I bring leaves."
        }, {
          "next": "heal",
          "text": "I am hurt."
        }, {
          "next": null,
          "text": "Later."
        }],
      "text": "Mae govannen. The hearth is warm. Our kingsfoil has all but failed — could you bring fresh leaves from the Chetwood?"
    }
  },
  "speaker": "miriel-vardameldo",
  "start": "start"
};
W.dialogues["orophin-mallorn"] = {
  "id": "orophin-mallorn",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "mallorn-started",
              "type": "flag",
              "value": true
            }, {
              "id": "the-last-mallorn",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }],
      "text": "Take this bow. Strike any who lay hand on the sapling."
    },
    "errand-receive": {
      "choices": [{
          "effects": [{
              "name": "errand-leg-3-delivered",
              "type": "flag",
              "value": true
            }, {
              "name": "errand-leg-4",
              "type": "flag",
              "value": true
            }, {
              "id": "keepers-errand-3",
              "type": "quest_complete"
            }, {
              "id": "keepers-errand-4",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }, {
          "next": "start",
          "text": "A moment."
        }],
      "text": "Hand it here. I wrap it in mallorn-leaf — it will not lose its way. Bear it now to Bard III in Dale."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "I will."
        }],
      "text": "The sapling stands. Keep the watch."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "mallorn-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 15,
              "faction": "galadhrim",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "Hannon le."
        }],
      "text": "The tree has rooted. Accept this lembas — little though it is."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "mallorn-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I will."
        }, {
          "cond": {
            "clauses": [{
                "name": "mallorn-started",
                "type": "flag"
              }, {
                "name": "mallorn-saved",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Has it held?"
        }, {
          "cond": {
            "name": "mallorn-saved",
            "type": "flag"
          },
          "next": "reward",
          "text": "The wood is well?"
        }, {
          "cond": {
            "clauses": [{
                "name": "errand-leg-3",
                "type": "flag"
              }, {
                "name": "errand-leg-4",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "errand-receive",
          "text": "I bear a Keeper's packet."
        }, {
          "next": null,
          "text": "Another time."
        }],
      "text": "Mae govannen. A young mallorn falters. Would you guard it a while?"
    }
  },
  "speaker": "haldirs-successor",
  "start": "start"
};
W.dialogues["oswin-watch"] = {
  "id": "oswin-watch",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "spies-started",
              "type": "flag",
              "value": true
            }, {
              "id": "easterling-spies",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I understand."
        }],
      "text": "Ride north-east, past the crooked tree. Do not be seen ere they are."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "spies-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 20,
              "type": "gold"
            }, {
              "delta": 15,
              "faction": "rohirrim",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "Aye."
        }],
      "text": "Clean work. The Mark owes you a cup."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "spies-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "I'll track them."
        }, {
          "cond": {
            "name": "spies-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "The spies are dealt with."
        }, {
          "next": null,
          "text": "Farewell."
        }],
      "text": "Up here, traveller. I have counted three strangers skirting the Wold by night. Will you track them?"
    }
  },
  "speaker": "oswin-scout",
  "start": "start"
};
W.dialogues["rosie-brew"] = {
  "id": "rosie-brew",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "I'll hurry."
        }],
      "text": "A pint's on the house when you return."
    },
    "drink": {
      "choices": [{
          "next": "start",
          "text": "Heart's lighter already."
        }],
      "text": "Bottoms up."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "I will."
        }],
      "text": "Mallorn honey — ask the Galadhrim kindly."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "ale-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 20,
              "type": "hp"
            }, {
              "delta": 15,
              "type": "gold"
            }, {
              "delta": 10,
              "faction": "hobbits",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "Lovely."
        }],
      "text": "Smooth as a summer evening, thanks to you. Here's your promised pint and a few silver besides."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "ale-started",
            "type": "not_flag"
          },
          "next": "task",
          "text": "I can help?"
        }, {
          "cond": {
            "clauses": [{
                "name": "ale-started",
                "type": "flag"
              }, {
                "name": "ale-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Honey found?"
        }, {
          "cond": {
            "name": "ale-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Was the ale fixed?"
        }, {
          "effects": [{
              "delta": -2,
              "type": "gold"
            }, {
              "delta": 10,
              "type": "hp"
            }],
          "next": "drink",
          "text": "Another pint."
        }, {
          "next": null,
          "text": "Another time."
        }],
      "text": "Evenin', traveller. Ale's a bit sour tonight — won't pass a hobbit's tongue."
    },
    "task": {
      "choices": [{
          "effects": [{
              "name": "ale-started",
              "type": "flag",
              "value": true
            }, {
              "id": "souring-ale",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I'll fetch a pot."
        }, {
          "next": "start",
          "text": "Tall errand."
        }],
      "text": "Mallorn honey — the real Elven kind. A pot of it fixes a cauldron. Try asking Orophin in Lothlórien."
    }
  },
  "speaker": "rosie-cotton-the-younger",
  "start": "start"
};
W.dialogues["sam-missing-mathom"] = {
  "id": "sam-missing-mathom",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "I'll be off."
        }],
      "text": "Bless you! The pond's south of the plaza."
    },
    "ask": {
      "choices": [{
          "effects": [{
              "name": "accepted-mathom",
              "type": "flag",
              "value": true
            }, {
              "id": "missing-mathom",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I'll bring it back."
        }, {
          "next": "start",
          "text": "Sorry, no."
        }],
      "text": "You see, I've misplaced a mathom — small copper thing, belonged to my great-grand-dad. I last saw it by the pond. Would you fetch it, if you spy it?"
    },
    "ask-found": {
      "choices": [{
          "effects": [{
              "name": "found-mathom",
              "type": "flag",
              "value": true
            }, {
              "id": "missing-mathom",
              "type": "quest_complete"
            }, {
              "delta": 15,
              "type": "gold"
            }, {
              "delta": 20,
              "type": "hp"
            }],
          "next": "return",
          "text": "Found it."
        }, {
          "next": "START",
          "text": "Not yet."
        }, {
          "next": null,
          "text": "Never mind."
        }],
      "text": "Any luck? The pond's south of the square."
    },
    "farewell": {
      "choices": [{
          "next": null,
          "text": "Likewise."
        }],
      "text": "Fair travels, friend."
    },
    "return": {
      "choices": [{
          "next": null,
          "text": "Happy to help."
        }],
      "text": "Oh splendid — my thanks! Here, take a few coppers and a bite to eat."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "accepted-mathom",
            "type": "not_flag"
          },
          "next": "ask",
          "text": "I have."
        }, {
          "cond": {
            "clauses": [{
                "name": "accepted-mathom",
                "type": "flag"
              }, {
                "name": "found-mathom",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "ask-found",
          "text": "Have you found it yet?"
        }, {
          "cond": {
            "name": "found-mathom",
            "type": "flag"
          },
          "next": "farewell",
          "text": "Safe pocketing to you."
        }, {
          "next": null,
          "text": "Not today."
        }],
      "text": "Ah, good day to you! Ah — have you a moment to help an old hobbit?"
    }
  },
  "speaker": "sam-gamgee-the-younger",
  "start": "start"
};
W.dialogues["thorin-relight"] = {
  "id": "thorin-relight",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "Aye."
        }],
      "text": "May the flame hold, friend."
    },
    "errand-receive": {
      "choices": [{
          "effects": [{
              "name": "errand-leg-2-delivered",
              "type": "flag",
              "value": true
            }, {
              "name": "errand-leg-3",
              "type": "flag",
              "value": true
            }, {
              "id": "keepers-errand-2",
              "type": "quest_complete"
            }, {
              "id": "keepers-errand-3",
              "type": "quest_start"
            }],
          "next": null,
          "text": "I will."
        }, {
          "next": "start",
          "text": "A moment."
        }],
      "text": "Hand it here. I'll seal a Dwarven rune to it. Bear the packet now to Orophin in Lothlórien."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Understood."
        }],
      "text": "Keep to the lamps and the lamps to you."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "relight-lamps-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 20,
              "faction": "dwarves-of-erebor",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Durin's sign shines again. Here, a rune-stone for your troubles."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "relight-lamps-started",
            "type": "not_flag"
          },
          "next": "task",
          "text": "Tell me."
        }, {
          "cond": {
            "clauses": [{
                "name": "relight-lamps-started",
                "type": "flag"
              }, {
                "name": "relight-lamps-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Still at it?"
        }, {
          "cond": {
            "name": "relight-lamps-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Mithril for ye."
        }, {
          "cond": {
            "clauses": [{
                "name": "errand-leg-2",
                "type": "flag"
              }, {
                "name": "errand-leg-3",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "errand-receive",
          "text": "I bear a Keeper's packet."
        }, {
          "next": null,
          "text": "Farewell."
        }],
      "text": "Welcome to the Doors of Durin, stranger. We've a task a stout arm might lend to."
    },
    "task": {
      "choices": [{
          "effects": [{
              "name": "relight-lamps-started",
              "type": "flag",
              "value": true
            }, {
              "id": "relight-the-lamps",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I'll light them."
        }, {
          "next": "start",
          "text": "Not my path."
        }],
      "text": "The old way-marker lamps along the east road have gone dark. Light them and we'll know the path is safe again."
    }
  },
  "speaker": "thorin-iv",
  "start": "start"
};
W.dialogues["tolman-pony"] = {
  "id": "tolman-pony",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "I will."
        }],
      "text": "Bring him back safe, mind."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Right."
        }],
      "text": "Try the pond — ponies love the sweet grass there."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "pony-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 10,
              "type": "gold"
            }, {
              "delta": 10,
              "faction": "shirriffs",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Stybba's home. Fredegar wept a tear. Here's a silver for your trouble."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "pony-started",
            "type": "not_flag"
          },
          "next": "task",
          "text": "Where last seen?"
        }, {
          "cond": {
            "clauses": [{
                "name": "pony-started",
                "type": "flag"
              }, {
                "name": "pony-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Pony found?"
        }, {
          "cond": {
            "name": "pony-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "All returned."
        }, {
          "next": null,
          "text": "Good day."
        }],
      "text": "Afternoon. Got a pony wandered off — Master Fredegar's Stybba. Could you bring him in?"
    },
    "task": {
      "choices": [{
          "effects": [{
              "name": "pony-started",
              "type": "flag",
              "value": true
            }, {
              "id": "missing-pony",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I'll look."
        }, {
          "next": "start",
          "text": "Not today."
        }],
      "text": "South of the plaza, near the pond. Shouldn't be far."
    }
  },
  "speaker": "tolman-smallburrow",
  "start": "start"
};
W.dialogues["warden-ash"] = {
  "id": "warden-ash",
  "nodes": {
    "accept": {
      "choices": [{
          "effects": [{
              "name": "ash-started",
              "type": "flag",
              "value": true
            }, {
              "id": "ash-and-ember",
              "type": "quest_start"
            }],
          "next": null,
          "text": "Consider it done."
        }],
      "text": "South of the watchfort. Burn it out."
    },
    "errand-final": {
      "choices": [{
          "effects": [{
              "name": "errand-leg-7-delivered",
              "type": "flag",
              "value": true
            }, {
              "name": "errand-leg-8",
              "type": "flag",
              "value": true
            }, {
              "name": "errand-leg-8-delivered",
              "type": "flag",
              "value": true
            }, {
              "id": "keepers-errand-7",
              "type": "quest_complete"
            }, {
              "id": "keepers-errand-8",
              "type": "quest_start"
            }, {
              "id": "keepers-errand-8",
              "type": "quest_complete"
            }, {
              "delta": 100,
              "type": "gold"
            }, {
              "delta": 25,
              "faction": "reunited-kingdom",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "It is done."
        }],
      "text": "At last. The seven seals — Bree, Imladris, Khazad, Lórien, Erebor, Mark, Anor — and now the Black Gate. The packet bears a single line: 'The watch endures.' You have woven the realms anew, Keeper."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Aye."
        }],
      "text": "No shade must follow you back."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "ash-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 25,
              "faction": "reunited-kingdom",
              "type": "faction_rep"
            }, {
              "delta": 30,
              "type": "gold"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "The Kingdom sends her thanks — and a sword."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "ash-started",
            "type": "not_flag"
          },
          "next": "accept",
          "text": "Where?"
        }, {
          "cond": {
            "clauses": [{
                "name": "ash-started",
                "type": "flag"
              }, {
                "name": "ash-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Still stirring?"
        }, {
          "cond": {
            "name": "ash-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "Fire is out?"
        }, {
          "cond": {
            "clauses": [{
                "name": "errand-leg-7",
                "type": "flag"
              }, {
                "name": "errand-leg-8",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "errand-final",
          "text": "I bear a Keeper's packet."
        }, {
          "next": null,
          "text": "Not today."
        }],
      "text": "You pass the gate at a good hour. We've a warren that must be cleared."
    }
  },
  "speaker": "warden-of-morannon",
  "start": "start"
};
W.dialogues["willowbark-kingsfoil"] = {
  "id": "willowbark-kingsfoil",
  "nodes": {
    "accept": {
      "choices": [{
          "next": null,
          "text": "Aye."
        }],
      "text": "Mind the brambles."
    },
    "progress": {
      "choices": [{
          "next": "start",
          "text": "Right."
        }],
      "text": "Whitish flowers. Thin leaves. Smells of old summer."
    },
    "reward": {
      "choices": [{
          "effects": [{
              "name": "kingsfoil-rewarded",
              "type": "flag",
              "value": true
            }, {
              "delta": 25,
              "type": "hp"
            }, {
              "delta": 10,
              "type": "gold"
            }, {
              "delta": 10,
              "faction": "bree-folk",
              "type": "faction_rep"
            }],
          "next": null,
          "text": "My thanks."
        }],
      "text": "Bless you. Take this phial — I'll ready a salve for you another day."
    },
    "start": {
      "choices": [{
          "cond": {
            "name": "kingsfoil-started",
            "type": "not_flag"
          },
          "next": "task",
          "text": "Where in the Chetwood?"
        }, {
          "cond": {
            "clauses": [{
                "name": "kingsfoil-started",
                "type": "flag"
              }, {
                "name": "kingsfoil-done",
                "type": "not_flag"
              }],
            "type": "and"
          },
          "next": "progress",
          "text": "Still looking?"
        }, {
          "cond": {
            "name": "kingsfoil-done",
            "type": "flag"
          },
          "next": "reward",
          "text": "I've the bundle."
        }, {
          "next": null,
          "text": "Not today, gaffer."
        }],
      "text": "Eh? You've the look of a walker. My kingsfoil stock's run thin — would you cut a fresh bundle in the Chetwood?"
    },
    "task": {
      "choices": [{
          "effects": [{
              "name": "kingsfoil-started",
              "type": "flag",
              "value": true
            }, {
              "id": "kingsfoil-in-chetwood",
              "type": "quest_start"
            }],
          "next": "accept",
          "text": "I'll bring a bundle."
        }, {
          "next": "start",
          "text": "Not my errand."
        }],
      "text": "North of town, a mile or two. Look for the thin-leaved plant with white flowers."
    }
  },
  "speaker": "old-willowbark",
  "start": "start"
};
