// GENERATED by build.js — do not edit by hand.

W.encounters["fading-scouts"] = {
  "enemies": [{
      "count": 3,
      "type": "orc"
    }],
  "id": "fading-scouts",
  "loot_table": [{
      "item": "lembas",
      "max": 1,
      "min": 1,
      "weight": 2
    }],
  "narrative": "Orcs still creep through the hills north of Imladris. Keep your blade loose.",
  "once": false,
  "region": "eriador-rivendell",
  "tags": ["patrol", "low-risk"],
  "trigger": "on_enter_region",
  "type": "scatter"
};
