// GENERATED by build.js — do not edit by hand.

W.encounters["easterling-raid"] = {
  "enemies": [{
      "count": 4,
      "tag": "easterling-scout",
      "type": "orc"
    }],
  "id": "easterling-raid",
  "loot_table": [{
      "item": "waybread",
      "max": 1,
      "min": 1,
      "weight": 2
    }, {
      "item": "spear-rohan",
      "max": 1,
      "min": 1,
      "weight": 1
    }],
  "narrative": "Easterling riders still prowl the Wold. Keep to the road if you ride unarmed.",
  "once": false,
  "region": "rohan",
  "tags": ["patrol", "wold"],
  "trigger": "on_enter_region",
  "type": "scatter"
};
W.encounters["fading-scouts"] = {
  "enemies": [{
      "count": 3,
      "type": "orc"
    }],
  "id": "fading-scouts",
  "loot_table": [{
      "item": "lembas",
      "max": 1,
      "min": 1,
      "weight": 2
    }],
  "narrative": "Orcs still creep through the hills north of Imladris. Keep your blade loose.",
  "once": false,
  "region": "eriador-rivendell",
  "tags": ["patrol", "low-risk"],
  "trigger": "on_enter_region",
  "type": "scatter"
};
