// GENERATED by build.js — do not edit by hand.

W.factions["bree-folk"] = {
  "allies": ["rangers-of-the-north", "hobbits"],
  "banner_color": "#8a6a3a",
  "id": "bree-folk",
  "name": "Folk of Bree",
  "territories": ["bree-land"]
};
W.factions["citadel-guard"] = {
  "allies": ["reunited-kingdom"],
  "banner_color": "#d4a82a",
  "id": "citadel-guard",
  "name": "Citadel Guard",
  "territories": ["gondor-south"]
};
W.factions["dwarves-of-erebor"] = {
  "allies": ["reunited-kingdom", "rohirrim"],
  "banner_color": "#c4801a",
  "enemies": ["orc-remnant"],
  "id": "dwarves-of-erebor",
  "name": "Dwarves of Erebor",
  "territories": ["moria-hollin", "dale-erebor"]
};
W.factions["easterling-holdouts"] = {
  "banner_color": "#7a3a2a",
  "enemies": ["reunited-kingdom", "rohirrim"],
  "id": "easterling-holdouts",
  "name": "Easterling Holdouts",
  "territories": ["rohan", "mordor-ruin"]
};
W.factions["galadhrim"] = {
  "allies": ["imladris-elves", "reunited-kingdom"],
  "banner_color": "#c8e0a0",
  "id": "galadhrim",
  "name": "Galadhrim",
  "territories": ["lothlorien-anduin"]
};
W.factions["haradrim-holdouts"] = {
  "banner_color": "#a06030",
  "enemies": ["reunited-kingdom"],
  "id": "haradrim-holdouts",
  "name": "Haradrim Holdouts"
};
W.factions["hobbits"] = {
  "allies": ["rangers-of-the-north", "shirriffs", "bree-folk"],
  "banner_color": "#6a8a3a",
  "id": "hobbits",
  "name": "Hobbits of the Shire",
  "territories": ["shire"]
};
W.factions["imladris-elves"] = {
  "allies": ["rangers-of-the-north", "galadhrim", "reunited-kingdom"],
  "banner_color": "#e0e0ff",
  "id": "imladris-elves",
  "name": "Elves of Imladris",
  "territories": ["eriador-rivendell"]
};
W.factions["orc-remnant"] = {
  "banner_color": "#4a2a2a",
  "enemies": ["reunited-kingdom", "rangers-of-the-north", "rohirrim", "dwarves-of-erebor", "hobbits", "imladris-elves", "galadhrim"],
  "id": "orc-remnant",
  "name": "Orc Remnant",
  "territories": ["mordor-ruin", "moria-hollin"]
};
W.factions["rangers-of-the-north"] = {
  "allies": ["reunited-kingdom", "hobbits", "imladris-elves"],
  "banner_color": "#3a4a5a",
  "enemies": ["orc-remnant"],
  "id": "rangers-of-the-north",
  "name": "Rangers of the North",
  "territories": ["eriador-rivendell", "bree-land", "shire"]
};
W.factions["reunited-kingdom"] = {
  "allies": ["rangers-of-the-north", "rohirrim", "dwarves-of-erebor", "imladris-elves", "galadhrim", "hobbits", "bree-folk"],
  "banner_color": "#f0e8d0",
  "enemies": ["orc-remnant", "easterling-holdouts", "haradrim-holdouts"],
  "id": "reunited-kingdom",
  "name": "Reunited Kingdom",
  "territories": ["gondor-south", "mordor-ruin"]
};
W.factions["rohirrim"] = {
  "allies": ["reunited-kingdom", "dwarves-of-erebor"],
  "banner_color": "#3a7a3a",
  "enemies": ["easterling-holdouts", "orc-remnant"],
  "id": "rohirrim",
  "name": "Rohirrim",
  "territories": ["rohan"]
};
W.factions["shirriffs"] = {
  "allies": ["hobbits"],
  "banner_color": "#d4a82a",
  "id": "shirriffs",
  "name": "The Shirriffs",
  "territories": ["shire"]
};
