// GENERATED by build.js — do not edit by hand.

W.items["axe-dwarven"] = {
  "icon_color": "#c4801a",
  "id": "axe-dwarven",
  "name": "Dwarven Battle-axe",
  "rarity": "uncommon",
  "slot": "melee",
  "stats": {
    "atk": 17
  },
  "type": "weapon"
};
W.items["bow-of-lorien"] = {
  "crafted_by": "galadhrim",
  "icon_color": "#c8e0a0",
  "id": "bow-of-lorien",
  "name": "Bow of Lórien",
  "rarity": "rare",
  "slot": "ranged",
  "stats": {
    "atk": 14,
    "range": 220
  },
  "type": "weapon"
};
W.items["bow-yew"] = {
  "icon_color": "#8a6a3a",
  "id": "bow-yew",
  "name": "Yew Bow",
  "rarity": "common",
  "slot": "ranged",
  "stats": {
    "atk": 10,
    "range": 180
  },
  "type": "weapon"
};
W.items["dwarf-bread"] = {
  "icon_color": "#c4801a",
  "id": "dwarf-bread",
  "name": "Dwarf Bread",
  "rarity": "common",
  "slot": "none",
  "stats": {
    "on_use": "heal 30"
  },
  "type": "consumable"
};
W.items["elven-cloak"] = {
  "crafted_by": "galadhrim",
  "icon_color": "#6a8a3a",
  "id": "elven-cloak",
  "name": "Elven Cloak",
  "rarity": "rare",
  "slot": "body",
  "stats": {
    "def": 1,
    "stealth": 0.25
  },
  "type": "cloak"
};
W.items["elvenbread-fresh"] = {
  "icon_color": "#e8d98a",
  "id": "elvenbread-fresh",
  "name": "Fresh Elven-bread",
  "rarity": "uncommon",
  "slot": "none",
  "stats": {
    "on_use": "heal 55"
  },
  "type": "consumable"
};
W.items["lembas"] = {
  "icon_color": "#c8e0a0",
  "id": "lembas",
  "name": "Lembas",
  "rarity": "uncommon",
  "slot": "none",
  "stats": {
    "on_use": "heal 35"
  },
  "type": "consumable"
};
W.items["mathom"] = {
  "icon_color": "#a0a080",
  "id": "mathom",
  "name": "Mathom",
  "rarity": "common",
  "slot": "none",
  "type": "lore"
};
W.items["meduseld-mead"] = {
  "icon_color": "#d4a82a",
  "id": "meduseld-mead",
  "name": "Meduseld Mead",
  "rarity": "common",
  "slot": "none",
  "stats": {
    "on_use": "heal 25"
  },
  "type": "consumable"
};
W.items["phial-of-galadriel"] = {
  "crafted_by": "galadhrim",
  "icon_color": "#e0e0ff",
  "id": "phial-of-galadriel",
  "name": "Phial of Galadriel",
  "rarity": "unique",
  "slot": "trinket",
  "stats": {
    "on_use": "banish-shade 60"
  },
  "type": "light"
};
W.items["rope"] = {
  "icon_color": "#c8c0a0",
  "id": "rope",
  "name": "Elven Rope",
  "rarity": "common",
  "slot": "none",
  "type": "key"
};
W.items["rune-stone"] = {
  "icon_color": "#c4801a",
  "id": "rune-stone",
  "name": "Dwarven Rune-stone",
  "rarity": "uncommon",
  "slot": "trinket",
  "stats": {
    "def": 1
  },
  "type": "lore"
};
W.items["shield-dwarven"] = {
  "icon_color": "#c4801a",
  "id": "shield-dwarven",
  "name": "Dwarven Shield",
  "rarity": "uncommon",
  "slot": "off",
  "stats": {
    "def": 6
  },
  "type": "armor"
};
W.items["shield-gondor"] = {
  "icon_color": "#f0e8d0",
  "id": "shield-gondor",
  "name": "Citadel Shield",
  "rarity": "common",
  "slot": "off",
  "stats": {
    "def": 5
  },
  "type": "armor"
};
W.items["shield-rohan"] = {
  "icon_color": "#3a7a3a",
  "id": "shield-rohan",
  "name": "Rohirric Shield",
  "rarity": "common",
  "slot": "off",
  "stats": {
    "def": 4
  },
  "type": "armor"
};
W.items["short-blade"] = {
  "icon_color": "#8a8a88",
  "id": "short-blade",
  "name": "Hobbit's Short-Blade",
  "rarity": "common",
  "slot": "melee",
  "stats": {
    "atk": 8
  },
  "type": "weapon"
};
W.items["sling"] = {
  "icon_color": "#8a8a88",
  "id": "sling",
  "name": "Hobbit Sling",
  "rarity": "common",
  "slot": "ranged",
  "stats": {
    "atk": 6,
    "range": 120
  },
  "type": "weapon"
};
W.items["spear-rohan"] = {
  "icon_color": "#3a7a3a",
  "id": "spear-rohan",
  "name": "Rohirric Spear",
  "rarity": "uncommon",
  "slot": "melee",
  "stats": {
    "atk": 13,
    "range": 38
  },
  "type": "weapon"
};
W.items["sword-elven"] = {
  "icon_color": "#c8d8e8",
  "id": "sword-elven",
  "name": "Elven Blade",
  "rarity": "uncommon",
  "slot": "melee",
  "stats": {
    "atk": 14
  },
  "type": "weapon"
};
W.items["sword-gondor"] = {
  "icon_color": "#f0e8d0",
  "id": "sword-gondor",
  "name": "Gondorian Longsword",
  "rarity": "uncommon",
  "slot": "melee",
  "stats": {
    "atk": 15
  },
  "type": "weapon"
};
W.items["waybread"] = {
  "icon_color": "#c4a06a",
  "id": "waybread",
  "name": "Waybread",
  "rarity": "common",
  "slot": "none",
  "stats": {
    "on_use": "heal 20"
  },
  "type": "consumable"
};
