// GENERATED by build.js — do not edit by hand.

W.npcs["bard-iii"] = {
  "dialogue": "bard-iron",
  "disposition": "friendly",
  "faction": "dwarves-of-erebor",
  "id": "bard-iii",
  "location": "region:dale-erebor",
  "name": "Bard III",
  "quest_hooks": ["iron-for-the-south"],
  "role": "king-of-dale",
  "spawn_pos": {
    "x": 24,
    "y": 24
  }
};
W.npcs["barliman-butterbur-ii"] = {
  "dialogue": "barliman-welcome",
  "disposition": "friendly",
  "faction": "bree-folk",
  "id": "barliman-butterbur-ii",
  "location": "region:bree-land",
  "name": "Barliman Butterbur II",
  "quest_hooks": ["strangers-on-the-greenway"],
  "role": "innkeeper",
  "spawn_pos": {
    "x": 20,
    "y": 20
  }
};
W.npcs["elrohir"] = {
  "dialogue": "elrohir-books",
  "disposition": "friendly",
  "faction": "imladris-elves",
  "id": "elrohir",
  "location": "region:eriador-rivendell",
  "name": "Elrohir",
  "quest_hooks": ["the-books-of-elrond"],
  "role": "lore-keeper",
  "spawn_pos": {
    "x": 24,
    "y": 24
  }
};
W.npcs["eomers-reeve"] = {
  "dialogue": "deorwin-hoofbeats",
  "disposition": "friendly",
  "faction": "rohirrim",
  "id": "eomers-reeve",
  "location": "region:rohan",
  "name": "Déorwin, Reeve of Edoras",
  "quest_hooks": ["hoofbeats-in-the-wold"],
  "role": "reeve",
  "spawn_pos": {
    "x": 24,
    "y": 24
  }
};
W.npcs["faramirs-steward"] = {
  "dialogue": "beregond-bridge",
  "disposition": "friendly",
  "faction": "reunited-kingdom",
  "id": "faramirs-steward",
  "location": "region:gondor-south",
  "name": "Beregond the Younger",
  "quest_hooks": ["bridge-of-stone"],
  "role": "steward",
  "spawn_pos": {
    "x": 24,
    "y": 24
  }
};
W.npcs["goldberry"] = {
  "dialogue": "goldberry-wight",
  "disposition": "friendly",
  "faction": "none",
  "id": "goldberry",
  "location": "region:old-forest",
  "name": "Goldberry",
  "quest_hooks": ["a-wight-returns"],
  "role": "river-daughter",
  "spawn_pos": {
    "x": 24,
    "y": 24
  }
};
W.npcs["haldirs-successor"] = {
  "dialogue": "orophin-mallorn",
  "disposition": "friendly",
  "faction": "galadhrim",
  "id": "haldirs-successor",
  "location": "region:lothlorien-anduin",
  "name": "Orophin the Grey",
  "quest_hooks": ["the-last-mallorn"],
  "role": "march-warden",
  "spawn_pos": {
    "x": 24,
    "y": 24
  }
};
W.npcs["lindir"] = {
  "dialogue": "lindir-verse",
  "disposition": "friendly",
  "faction": "imladris-elves",
  "id": "lindir",
  "location": "region:eriador-rivendell",
  "name": "Lindir",
  "quest_hooks": ["a-forgotten-verse"],
  "role": "loremaster-singer",
  "spawn_pos": {
    "x": 20,
    "y": 24
  }
};
W.npcs["old-willowbark"] = {
  "dialogue": "willowbark-kingsfoil",
  "disposition": "friendly",
  "faction": "bree-folk",
  "id": "old-willowbark",
  "location": "region:bree-land",
  "name": "Old Willowbark",
  "quest_hooks": ["kingsfoil-in-chetwood"],
  "role": "herbalist",
  "spawn_pos": {
    "x": 17,
    "y": 18
  }
};
W.npcs["rosie-cotton-the-younger"] = {
  "dialogue": "rosie-brew",
  "disposition": "friendly",
  "faction": "hobbits",
  "id": "rosie-cotton-the-younger",
  "location": "region:shire",
  "name": "Rosie Cotton-the-Younger",
  "quest_hooks": ["souring-ale"],
  "role": "tavern-keeper",
  "spawn_pos": {
    "x": 28,
    "y": 22
  }
};
W.npcs["sam-gamgee-the-younger"] = {
  "dialogue": "sam-missing-mathom",
  "disposition": "friendly",
  "faction": "hobbits",
  "id": "sam-gamgee-the-younger",
  "location": "region:shire",
  "name": "Sam Gamgee-the-Younger",
  "quest_hooks": ["missing-mathom"],
  "role": "mayor-of-hobbiton",
  "spawn_pos": {
    "x": 22,
    "y": 21
  }
};
W.npcs["thorin-iv"] = {
  "dialogue": "thorin-relight",
  "disposition": "friendly",
  "faction": "dwarves-of-erebor",
  "id": "thorin-iv",
  "location": "region:moria-hollin",
  "name": "Thorin IV",
  "quest_hooks": ["relight-the-lamps"],
  "role": "gate-keeper",
  "spawn_pos": {
    "x": 24,
    "y": 24
  }
};
W.npcs["tolman-smallburrow"] = {
  "dialogue": "tolman-pony",
  "disposition": "friendly",
  "faction": "shirriffs",
  "id": "tolman-smallburrow",
  "location": "region:shire",
  "name": "Sheriff Tolman Smallburrow",
  "quest_hooks": ["missing-pony"],
  "role": "shirriff-captain",
  "spawn_pos": {
    "x": 18,
    "y": 22
  }
};
W.npcs["warden-of-morannon"] = {
  "dialogue": "warden-ash",
  "disposition": "friendly",
  "faction": "reunited-kingdom",
  "id": "warden-of-morannon",
  "location": "region:mordor-ruin",
  "name": "Warden of the Black Gate",
  "quest_hooks": ["ash-and-ember"],
  "role": "warden",
  "spawn_pos": {
    "x": 24,
    "y": 24
  }
};
