// GENERATED by build.js — do not edit by hand.

W.npcs["barliman-butterbur-ii"] = {
  "dialogue": "barliman-welcome",
  "disposition": "friendly",
  "faction": "bree-folk",
  "id": "barliman-butterbur-ii",
  "location": "region:bree-land",
  "name": "Barliman Butterbur II",
  "quest_hooks": ["strangers-on-the-greenway"],
  "role": "innkeeper",
  "spawn_pos": {
    "x": 20,
    "y": 20
  }
};
W.npcs["sam-gamgee-the-younger"] = {
  "dialogue": "sam-missing-mathom",
  "disposition": "friendly",
  "faction": "hobbits",
  "id": "sam-gamgee-the-younger",
  "location": "region:shire",
  "name": "Sam Gamgee-the-Younger",
  "quest_hooks": ["missing-mathom"],
  "role": "mayor-of-hobbiton",
  "spawn_pos": {
    "x": 22,
    "y": 21
  }
};
