// GENERATED by build.js — do not edit by hand.

W.quests["a-forgotten-verse"] = {
  "giver": "npc:lindir",
  "id": "a-forgotten-verse",
  "rewards": {
    "gold": 15,
    "rep": [{
        "delta": 15,
        "faction": "imladris-elves"
      }]
  },
  "steps": [{
      "hint": "Search the Imladris scriptorium, then return to Lindir.",
      "id": "seek",
      "target": "verse-done",
      "type": "flag"
    }],
  "summary": "Lindir has lost a line of his latest song. Search the Imladris annals.",
  "title": "A Forgotten Verse"
};
W.quests["a-wight-returns"] = {
  "giver": "npc:goldberry",
  "id": "a-wight-returns",
  "rewards": {
    "gold": 15,
    "rep": [{
        "delta": 10,
        "faction": "rangers-of-the-north"
      }]
  },
  "steps": [],
  "summary": "A barrow-wight has woken on the Downs. Put it to rest.",
  "title": "A Wight Returns"
};
W.quests["ash-and-ember"] = {
  "giver": "npc:warden-of-morannon",
  "id": "ash-and-ember",
  "rewards": {
    "gold": 30,
    "rep": [{
        "delta": 25,
        "faction": "reunited-kingdom"
      }]
  },
  "steps": [],
  "summary": "Burn out an orc-warren south of the Morannon watchfort.",
  "title": "Ash and Ember"
};
W.quests["bridge-of-stone"] = {
  "giver": "npc:faramirs-steward",
  "id": "bridge-of-stone",
  "rewards": {
    "gold": 25,
    "rep": [{
        "delta": 20,
        "faction": "reunited-kingdom"
      }]
  },
  "steps": [],
  "summary": "Drive bandits off the rebuilt southern bridge at Osgiliath.",
  "title": "Bridge of Stone"
};
W.quests["easterling-spies"] = {
  "giver": "npc:oswin-scout",
  "id": "easterling-spies",
  "rewards": {
    "gold": 20,
    "rep": [{
        "delta": 15,
        "faction": "rohirrim"
      }]
  },
  "steps": [{
      "count": 3,
      "hint": "Slay three raiders on the Wold north-east of Edoras.",
      "id": "hunt",
      "target": "orc",
      "type": "kill"
    }, {
      "hint": "Return to Oswin at the Watchtower of Edoras.",
      "id": "report",
      "target": "spies-rewarded",
      "type": "flag"
    }],
  "summary": "Oswin has seen strangers slipping past the Wold by night. Track them down and silence them.",
  "tags": ["combat", "patrol"],
  "title": "Easterling Spies"
};
W.quests["hoofbeats-in-the-wold"] = {
  "giver": "npc:eomers-reeve",
  "id": "hoofbeats-in-the-wold",
  "rewards": {
    "gold": 20,
    "rep": [{
        "delta": 15,
        "faction": "rohirrim"
      }]
  },
  "steps": [],
  "summary": "Drive off Easterling raiders in the North Wold.",
  "title": "Hoofbeats in the Wold"
};
W.quests["horse-of-the-mark"] = {
  "giver": "npc:leofric-stablemaster",
  "id": "horse-of-the-mark",
  "rewards": {
    "gold": 25,
    "rep": [{
        "delta": 10,
        "faction": "rohirrim"
      }]
  },
  "steps": [{
      "hint": "Ride east of Edoras, along the stream, to find the bay colt.",
      "id": "find",
      "target": "lost-horse-found",
      "type": "flag"
    }, {
      "hint": "Return Fréawine to Léofric at the Stables of the Mark.",
      "id": "return",
      "target": "lost-horse-rewarded",
      "type": "flag"
    }],
  "summary": "Fréawine, a bay colt of the Stables of the Mark, broke his tether. Find him east of Edoras and return him to Léofric.",
  "tags": ["rescue", "fetch"],
  "title": "Horse of the Mark"
};
W.quests["iron-for-the-south"] = {
  "giver": "npc:bard-iii",
  "id": "iron-for-the-south",
  "rewards": {
    "gold": 30,
    "rep": [{
        "delta": 15,
        "faction": "dwarves-of-erebor"
      }]
  },
  "steps": [],
  "summary": "Escort a caravan of iron-work from Dale toward Gondor.",
  "title": "Iron for the South"
};
W.quests["keepers-errand-1"] = {
  "arc": "keepers-errand",
  "giver": "npc:barliman-butterbur-ii",
  "id": "keepers-errand-1",
  "rewards": {
    "gold": 10,
    "rep": [{
        "delta": 5,
        "faction": "rangers-of-the-north"
      }]
  },
  "steps": [{
      "hint": "Bring the letter to Elrohir in Rivendell.",
      "id": "travel",
      "target": "errand-leg-1-delivered",
      "type": "flag"
    }],
  "summary": "Carry Halbarad's sealed letter east to Elrohir at Rivendell.",
  "title": "The Letter Sealed"
};
W.quests["keepers-errand-2"] = {
  "arc": "keepers-errand",
  "giver": "npc:elrohir",
  "id": "keepers-errand-2",
  "rewards": {
    "gold": 10,
    "rep": [{
        "delta": 5,
        "faction": "imladris-elves"
      }]
  },
  "steps": [{
      "hint": "Bring the packet to Thorin IV at the Doors of Durin.",
      "id": "travel",
      "target": "errand-leg-2-delivered",
      "type": "flag"
    }],
  "summary": "Carry the packet — now bearing Elven counsel — east to Thorin IV at Moria's West-gate.",
  "title": "To the Doors of Durin"
};
W.quests["keepers-errand-3"] = {
  "arc": "keepers-errand",
  "giver": "npc:thorin-iv",
  "id": "keepers-errand-3",
  "rewards": {
    "gold": 10,
    "rep": [{
        "delta": 5,
        "faction": "dwarves-of-erebor"
      }]
  },
  "steps": [{
      "hint": "Bring the packet to Orophin in Lothlórien.",
      "id": "travel",
      "target": "errand-leg-3-delivered",
      "type": "flag"
    }],
  "summary": "Carry the packet — now sealed with Dwarven runes — south to Orophin in Lothlórien.",
  "title": "To the Golden Wood"
};
W.quests["keepers-errand-4"] = {
  "arc": "keepers-errand",
  "giver": "npc:haldirs-successor",
  "id": "keepers-errand-4",
  "rewards": {
    "gold": 10,
    "rep": [{
        "delta": 5,
        "faction": "galadhrim"
      }]
  },
  "steps": [{
      "hint": "Bring the packet to Bard III in Dale.",
      "id": "travel",
      "target": "errand-leg-4-delivered",
      "type": "flag"
    }],
  "summary": "Carry the packet — wrapped in mallorn-leaf — east to Bard III in Dale.",
  "title": "To the Lonely Mountain"
};
W.quests["keepers-errand-5"] = {
  "arc": "keepers-errand",
  "giver": "npc:bard-iii",
  "id": "keepers-errand-5",
  "rewards": {
    "gold": 10,
    "rep": [{
        "delta": 5,
        "faction": "dwarves-of-erebor"
      }]
  },
  "steps": [{
      "hint": "Bring the packet to the Reeve of Edoras.",
      "id": "travel",
      "target": "errand-leg-5-delivered",
      "type": "flag"
    }],
  "summary": "Carry the packet — now thicker with Ereborian script — south to Déorwin at Edoras.",
  "title": "To the Mark"
};
W.quests["keepers-errand-6"] = {
  "arc": "keepers-errand",
  "giver": "npc:eomers-reeve",
  "id": "keepers-errand-6",
  "rewards": {
    "gold": 10,
    "rep": [{
        "delta": 5,
        "faction": "rohirrim"
      }]
  },
  "steps": [{
      "hint": "Bring the packet to Beregond the Younger in Osgiliath.",
      "id": "travel",
      "target": "errand-leg-6-delivered",
      "type": "flag"
    }],
  "summary": "Carry the packet — now bound with the white horse seal — east to Beregond at Osgiliath.",
  "title": "To the White Tower"
};
W.quests["keepers-errand-7"] = {
  "arc": "keepers-errand",
  "giver": "npc:faramirs-steward",
  "id": "keepers-errand-7",
  "rewards": {
    "gold": 10,
    "rep": [{
        "delta": 10,
        "faction": "reunited-kingdom"
      }]
  },
  "steps": [{
      "hint": "Bring the packet to the Warden of the Black Gate.",
      "id": "travel",
      "target": "errand-leg-7-delivered",
      "type": "flag"
    }],
  "summary": "Carry the packet — now sealed with the white tree — east to the Warden at Morannon.",
  "title": "To the Black Gate"
};
W.quests["keepers-errand-8"] = {
  "arc": "keepers-errand",
  "giver": "npc:warden-of-morannon",
  "id": "keepers-errand-8",
  "rewards": {
    "gold": 100,
    "rep": [{
        "delta": 25,
        "faction": "reunited-kingdom"
      }, {
        "delta": 25,
        "faction": "rangers-of-the-north"
      }]
  },
  "steps": [{
      "hint": "Receive the Warden's charge.",
      "id": "capstone",
      "target": "errand-leg-8-delivered",
      "type": "flag"
    }],
  "summary": "The Warden opens the packet at last. Its contents will shape the next age.",
  "title": "The Keeper's Charge"
};
W.quests["kingsfoil-for-imladris"] = {
  "giver": "npc:miriel-vardameldo",
  "id": "kingsfoil-for-imladris",
  "rewards": {
    "gold": 20,
    "items": ["elvenbread-fresh"],
    "rep": [{
        "delta": 10,
        "faction": "imladris-elves"
      }]
  },
  "steps": [{
      "hint": "Forage kingsfoil in the Chetwood (Bree-land, speak with Old Willowbark).",
      "id": "gather",
      "target": "kingsfoil-done",
      "type": "flag"
    }, {
      "hint": "Return the leaves to Míriel at the Healers' Hall.",
      "id": "deliver",
      "target": "kingsfoil-errand-rewarded",
      "type": "flag"
    }],
  "summary": "Míriel's athelas supply has failed. Gather fresh kingsfoil from the Chetwood and bring it to the Healers' Hall.",
  "tags": ["herbalism", "fetch"],
  "title": "Kingsfoil for Imladris"
};
W.quests["kingsfoil-in-chetwood"] = {
  "giver": "npc:old-willowbark",
  "id": "kingsfoil-in-chetwood",
  "rewards": {
    "gold": 10,
    "rep": [{
        "delta": 10,
        "faction": "bree-folk"
      }]
  },
  "steps": [{
      "hint": "Find kingsfoil in the Chetwood, then return to Old Willowbark.",
      "id": "gather",
      "target": "kingsfoil-done",
      "type": "flag"
    }],
  "summary": "Cut a bundle of kingsfoil for Old Willowbark in the Chetwood north of Bree.",
  "title": "Kingsfoil in the Chetwood"
};
W.quests["missing-mathom"] = {
  "classes_eligible": ["hobbit", "ranger-of-the-north"],
  "giver": "npc:sam-gamgee-the-younger",
  "id": "missing-mathom",
  "rewards": {
    "gold": 15,
    "rep": [{
        "delta": 10,
        "faction": "hobbits"
      }]
  },
  "steps": [],
  "summary": "Sam Gamgee-the-Younger has misplaced a family mathom near the Hobbiton pond.",
  "title": "Missing Mathom"
};
W.quests["missing-pony"] = {
  "giver": "npc:tolman-smallburrow",
  "id": "missing-pony",
  "rewards": {
    "gold": 10,
    "rep": [{
        "delta": 10,
        "faction": "shirriffs"
      }]
  },
  "steps": [{
      "hint": "Look for Stybba near the Hobbiton pond, then report to the Sheriff.",
      "id": "find",
      "target": "pony-done",
      "type": "flag"
    }],
  "summary": "Find Master Fredegar's runaway pony, Stybba, near the Hobbiton pond.",
  "title": "Missing Pony"
};
W.quests["relight-the-lamps"] = {
  "giver": "npc:thorin-iv",
  "id": "relight-the-lamps",
  "rewards": {
    "gold": 20,
    "rep": [{
        "delta": 20,
        "faction": "dwarves-of-erebor"
      }]
  },
  "steps": [],
  "summary": "Light the way-marker lamps along Moria's East Road.",
  "title": "Relight the Lamps"
};
W.quests["souring-ale"] = {
  "classes_eligible": ["hobbit", "ranger-of-the-north", "elf-noldor", "elf-silvan", "rohirrim", "dwarf", "gondorian", "dunadan"],
  "giver": "npc:rosie-cotton-the-younger",
  "id": "souring-ale",
  "rewards": {
    "gold": 15,
    "rep": [{
        "delta": 10,
        "faction": "hobbits"
      }]
  },
  "steps": [{
      "hint": "Ask Orophin in Lothlórien for mallorn honey, then return to Rosie.",
      "id": "fetch",
      "target": "ale-done",
      "type": "flag"
    }],
  "summary": "The Green Dragon's ale has soured. Fetch a pot of mallorn honey from Lothlórien.",
  "title": "Souring Ale"
};
W.quests["strangers-on-the-greenway"] = {
  "classes_eligible": ["ranger-of-the-north", "rohirrim", "gondorian", "dwarf", "elf-noldor", "hobbit"],
  "giver": "npc:barliman-butterbur-ii",
  "id": "strangers-on-the-greenway",
  "rewards": {
    "gold": 25,
    "rep": [{
        "delta": 10,
        "faction": "bree-folk"
      }, {
        "delta": 5,
        "faction": "rangers-of-the-north"
      }]
  },
  "steps": [],
  "summary": "Clear the orc-scouts prowling the Greenway south of Bree.",
  "title": "Strangers on the Greenway"
};
W.quests["the-books-of-elrond"] = {
  "giver": "npc:elrohir",
  "id": "the-books-of-elrond",
  "rewards": {
    "gold": 20,
    "rep": [{
        "delta": 20,
        "faction": "imladris-elves"
      }]
  },
  "steps": [],
  "summary": "Recover annals of Elrond left behind when his household sailed west.",
  "title": "The Books of Elrond"
};
W.quests["the-last-mallorn"] = {
  "giver": "npc:haldirs-successor",
  "id": "the-last-mallorn",
  "rewards": {
    "gold": 15,
    "rep": [{
        "delta": 15,
        "faction": "galadhrim"
      }]
  },
  "steps": [],
  "summary": "Protect a young mallorn sapling while it roots.",
  "title": "The Last Mallorn"
};
W.quests["the-lost-page"] = {
  "giver": "npc:erestor-the-younger",
  "id": "the-lost-page",
  "rewards": {
    "gold": 20,
    "rep": [{
        "delta": 10,
        "faction": "imladris-elves"
      }]
  },
  "steps": [{
      "hint": "Speak with Culunedhel in the Bruinen Archive, south of the road.",
      "id": "retrieve",
      "target": "lost-page-retrieved",
      "type": "flag"
    }, {
      "hint": "Return the page to Erestor in the scriptorium.",
      "id": "return",
      "target": "lost-page-done",
      "type": "flag"
    }],
  "summary": "A leaf of the Arnor charter-roll has slipped its binding. Retrieve it from the Bruinen Archive.",
  "tags": ["lore", "fetch"],
  "title": "The Lost Page"
};
