// GENERATED by build.js — do not edit by hand.

W.quests["a-wight-returns"] = {
  "giver": "npc:goldberry",
  "id": "a-wight-returns",
  "rewards": {
    "gold": 15,
    "rep": [{
        "delta": 10,
        "faction": "rangers-of-the-north"
      }]
  },
  "steps": [],
  "summary": "A barrow-wight has woken on the Downs. Put it to rest.",
  "title": "A Wight Returns"
};
W.quests["ash-and-ember"] = {
  "giver": "npc:warden-of-morannon",
  "id": "ash-and-ember",
  "rewards": {
    "gold": 30,
    "rep": [{
        "delta": 25,
        "faction": "reunited-kingdom"
      }]
  },
  "steps": [],
  "summary": "Burn out an orc-warren south of the Morannon watchfort.",
  "title": "Ash and Ember"
};
W.quests["bridge-of-stone"] = {
  "giver": "npc:faramirs-steward",
  "id": "bridge-of-stone",
  "rewards": {
    "gold": 25,
    "rep": [{
        "delta": 20,
        "faction": "reunited-kingdom"
      }]
  },
  "steps": [],
  "summary": "Drive bandits off the rebuilt southern bridge at Osgiliath.",
  "title": "Bridge of Stone"
};
W.quests["hoofbeats-in-the-wold"] = {
  "giver": "npc:eomers-reeve",
  "id": "hoofbeats-in-the-wold",
  "rewards": {
    "gold": 20,
    "rep": [{
        "delta": 15,
        "faction": "rohirrim"
      }]
  },
  "steps": [],
  "summary": "Drive off Easterling raiders in the North Wold.",
  "title": "Hoofbeats in the Wold"
};
W.quests["iron-for-the-south"] = {
  "giver": "npc:bard-iii",
  "id": "iron-for-the-south",
  "rewards": {
    "gold": 30,
    "rep": [{
        "delta": 15,
        "faction": "dwarves-of-erebor"
      }]
  },
  "steps": [],
  "summary": "Escort a caravan of iron-work from Dale toward Gondor.",
  "title": "Iron for the South"
};
W.quests["missing-mathom"] = {
  "classes_eligible": ["hobbit", "ranger-of-the-north"],
  "giver": "npc:sam-gamgee-the-younger",
  "id": "missing-mathom",
  "rewards": {
    "gold": 15,
    "rep": [{
        "delta": 10,
        "faction": "hobbits"
      }]
  },
  "steps": [],
  "summary": "Sam Gamgee-the-Younger has misplaced a family mathom near the Hobbiton pond.",
  "title": "Missing Mathom"
};
W.quests["relight-the-lamps"] = {
  "giver": "npc:thorin-iv",
  "id": "relight-the-lamps",
  "rewards": {
    "gold": 20,
    "rep": [{
        "delta": 20,
        "faction": "dwarves-of-erebor"
      }]
  },
  "steps": [],
  "summary": "Light the way-marker lamps along Moria's East Road.",
  "title": "Relight the Lamps"
};
W.quests["strangers-on-the-greenway"] = {
  "classes_eligible": ["ranger-of-the-north", "rohirrim", "gondorian", "dwarf", "elf-noldor", "hobbit"],
  "giver": "npc:barliman-butterbur-ii",
  "id": "strangers-on-the-greenway",
  "rewards": {
    "gold": 25,
    "rep": [{
        "delta": 10,
        "faction": "bree-folk"
      }, {
        "delta": 5,
        "faction": "rangers-of-the-north"
      }]
  },
  "steps": [],
  "summary": "Clear the orc-scouts prowling the Greenway south of Bree.",
  "title": "Strangers on the Greenway"
};
W.quests["the-books-of-elrond"] = {
  "giver": "npc:elrohir",
  "id": "the-books-of-elrond",
  "rewards": {
    "gold": 20,
    "rep": [{
        "delta": 20,
        "faction": "imladris-elves"
      }]
  },
  "steps": [],
  "summary": "Recover annals of Elrond left behind when his household sailed west.",
  "title": "The Books of Elrond"
};
W.quests["the-last-mallorn"] = {
  "giver": "npc:haldirs-successor",
  "id": "the-last-mallorn",
  "rewards": {
    "gold": 15,
    "rep": [{
        "delta": 15,
        "faction": "galadhrim"
      }]
  },
  "steps": [],
  "summary": "Protect a young mallorn sapling while it roots.",
  "title": "The Last Mallorn"
};
