// GENERATED by build.js — do not edit by hand.

W.quests["missing-mathom"] = {
  "classes_eligible": ["hobbit", "ranger-of-the-north"],
  "giver": "npc:sam-gamgee-the-younger",
  "id": "missing-mathom",
  "rewards": {
    "gold": 15,
    "rep": [{
        "delta": 10,
        "faction": "hobbits"
      }]
  },
  "steps": [],
  "summary": "Sam Gamgee-the-Younger has misplaced a family mathom near the Hobbiton pond.",
  "title": "Missing Mathom"
};
W.quests["strangers-on-the-greenway"] = {
  "classes_eligible": ["ranger-of-the-north", "rohirrim", "gondorian", "dwarf", "elf-noldor", "hobbit"],
  "giver": "npc:barliman-butterbur-ii",
  "id": "strangers-on-the-greenway",
  "rewards": {
    "gold": 25,
    "rep": [{
        "delta": 10,
        "faction": "bree-folk"
      }, {
        "delta": 5,
        "faction": "rangers-of-the-north"
      }]
  },
  "steps": [],
  "summary": "Clear the orc-scouts prowling the Greenway south of Bree.",
  "title": "Strangers on the Greenway"
};
