// GENERATED by build.js — do not edit by hand.

W.regions["bree-land"] = {
  "climate": "temperate",
  "era": "fourth-age-early",
  "factions_present": ["bree-folk", "rangers-of-the-north"],
  "id": "bree-land",
  "name": "Bree-land",
  "neighbors": {
    "east": "eriador-rivendell",
    "north": null,
    "south": "old-forest",
    "west": "shire"
  },
  "overworld_pos": {
    "x": 6,
    "y": 9
  },
  "spawn_point": {
    "x": 24,
    "y": 24
  },
  "tilemap": "bree-land",
  "tone": "crossroads-bustle"
};
W.regions["eriador-rivendell"] = {
  "climate": "temperate",
  "era": "fourth-age-early",
  "factions_present": ["imladris-elves", "rangers-of-the-north"],
  "id": "eriador-rivendell",
  "name": "Eriador & Rivendell",
  "neighbors": {
    "east": null,
    "north": null,
    "south": null,
    "west": "bree-land"
  },
  "overworld_pos": {
    "x": 8,
    "y": 9
  },
  "spawn_point": {
    "x": 24,
    "y": 24
  },
  "tilemap": "eriador-rivendell",
  "tone": "melancholy-quiet"
};
W.regions["old-forest"] = {
  "climate": "temperate",
  "era": "fourth-age-early",
  "factions_present": [],
  "id": "old-forest",
  "name": "The Old Forest",
  "neighbors": {
    "east": null,
    "north": "bree-land",
    "south": null,
    "west": null
  },
  "overworld_pos": {
    "x": 6,
    "y": 11
  },
  "spawn_point": {
    "x": 24,
    "y": 24
  },
  "tilemap": "old-forest",
  "tone": "haunted-green"
};
W.regions["shire"] = {
  "climate": "temperate",
  "era": "fourth-age-early",
  "factions_present": ["hobbits", "shirriffs"],
  "id": "shire",
  "name": "The Shire",
  "neighbors": {
    "east": "bree-land",
    "north": null,
    "south": null,
    "west": null
  },
  "overworld_pos": {
    "x": 4,
    "y": 9
  },
  "spawn_point": {
    "x": 22,
    "y": 22
  },
  "tilemap": "shire",
  "tone": "pastoral-cozy"
};
