// GENERATED by build.js — do not edit by hand.

W.settlements["bree"] = {
  "faction": "bree-folk",
  "id": "bree",
  "name": "Bree",
  "notable_buildings": [],
  "population": 900,
  "region": "bree-land",
  "ruler": "barliman-butterbur-ii",
  "tile_region": {
    "h": 13,
    "w": 15,
    "x": 15,
    "y": 17
  },
  "type": "town"
};
W.settlements["hobbiton"] = {
  "faction": "hobbits",
  "id": "hobbiton",
  "name": "Hobbiton",
  "notable_buildings": [],
  "population": 420,
  "region": "shire",
  "ruler": "sam-gamgee-the-younger",
  "tile_region": {
    "h": 9,
    "w": 13,
    "x": 17,
    "y": 18
  },
  "type": "village"
};
W.settlements["imladris"] = {
  "description": "|",
  "faction": "imladris-elves",
  "id": "imladris",
  "name": "Imladris",
  "notable_buildings": ["imladris-scriptorium", "hall-of-fire", "last-homely-house", "bruinen-archive", "healers-hall"],
  "population": 180,
  "region": "eriador-rivendell",
  "ruler": "elrohir",
  "tags": ["elven", "lore", "valley"],
  "tile_region": {
    "h": 14,
    "w": 22,
    "x": 15,
    "y": 17
  },
  "type": "town"
};
